// <auto-generated />
using DvSqlGenWeb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DvSqlGenWeb.Migrations
{
    [DbContext(typeof(RagDbContext))]
    [Migration("20250917051910_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("DvSqlGenWeb.Context.Models.Chunk", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dim")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Field")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionAlias")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synonyms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Field");

                    b.HasIndex("CardType", "SectionAlias");

                    b.ToTable("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
